version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'mpv'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306'
    volumes:
      - mpv_db:/var/lib/mysql
  webapp:
      depends_on:
          - "db"
      image: mpv:latest
      restart: always
      ports:
        - "5000:5000"
volumes:
  mpv_db:
